// <auto-generated />
namespace Pointer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class LC1013 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LC1013));
        
        string IMigrationMetadata.Id
        {
            get { return "201905140831208_LC1.013"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
